### ISSUE TITLE
The plug-in could not be loaded successfully

### ISSUE THREAD

**Issue by crescent-admin** [ValMobile/RealisticSurvival#17]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

您好，由于我的英语水平欠佳，使用了翻译软件，因此可能会出现一些奇怪的表达.

Hello, because my English level is poor and I have used translation software, some strange expressions may appear

插件版本为1.2.3-RELEASE

The plug-in version is 1.2.3-RELEASE

我的服务器版本是paper-1.18.2-388

My server version is paper-1.18.2-388

这个版本的插件在我的服务器上无法启动，而先前的版本（1.2.2）却可以正常运行.（报错信息在下面）

This version of the plug-in cannot be started on my server, while the previous version (1.2.2) can run normally. (The error message is shown below)

这是怎么回事呢？希望能得到解决，非常感谢！

What's going on here? I hope it can be solved, thank you very much!

### 📑 Reproduction Steps

[04:18:06 INFO]: [RealisticSurvival] Enabling RealisticSurvival v1.2.3-RELEASE
[04:18:07 INFO]: [RealisticSurvival] §6[Realistic Survival] §fInitializing §bIceandFire §fmodule
[04:18:07 INFO]: [RealisticSurvival] §6[Realistic Survival] §fInitializing §bSpartanWeaponry §fmodule
[04:18:08 INFO]: [RealisticSurvival] §6[Realistic Survival] §fInitializing §bBaubles §fmodule
[04:18:08 ERROR]: Error occurred while enabling RealisticSurvival v1.2.3-RELEASE (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.TADPOLE_BUCKET
        at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
        at org.bukkit.Material.valueOf(Material.java:106) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at me.val_mobile.utils.RSVItem.<init>(RSVItem.java:170) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at me.val_mobile.data.ItemManager.initialize(ItemManager.java:70) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at me.val_mobile.data.ItemManager.<init>(ItemManager.java:38) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at me.val_mobile.data.ModuleItems.<init>(ModuleItems.java:22) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at me.val_mobile.ntr.NtrModule.initialize(NtrModule.java:47) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at me.val_mobile.realisticsurvival.RealisticSurvivalPlugin.onEnable(RealisticSurvivalPlugin.java:97) ~[realisticsurvival-1.2.3-RELEASE.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:18:08 INFO]: [RealisticSurvival] Disabling RealisticSurvival v1.2.3-RELEASE
[04:18:08 INFO]: [RealisticSurvival] §6[Realistic Survival] §fShutting down §bIceandFire §fmodule
[04:18:08 INFO]: [RealisticSurvival] §6[Realistic Survival] §fShutting down §bNoTreePunching §fmodule
[04:18:08 INFO]: [RealisticSurvival] §6[Realistic Survival] §fShutting down §bBaubles §fmodule
[04:18:08 INFO]: [RealisticSurvival] §6[Realistic Survival] §fShutting down §bSpartanWeaponry §fmodule

### 💡 Expected Behavior

 to be loaded successfully

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Realistic Survival version

1.2.3-RELEASE

**Comment by ValMobile** [comment]
Hi, thanks for making the bug report. The error is caused by the plugin trying to enable ceramic tadpole buckets on 1.18.2, but tadpole buckets weren't added until 1.19. To fix this, try adding "v1_18_R3: false" below "Versions" of the "ceramic_tadpole_bucket" entry in notreepunching.yml.
<img width="182" alt="image" src="https://user-images.githubusercontent.com/58125835/206874521-0a7b0616-7112-4e29-9468-91b0813b6d9a.png">
