### ISSUE TITLE
An error occurred when using version 1.19.4

### ISSUE THREAD

**Issue by anxge** [ValMobile/RealisticSurvival#28]
### ❗ Checklist

- [X] I am using the official version of Realistic Survival and did not modify the jar.
- [X] I am using an up-to-date "dev-build" (not "Spigot") version of Realistic Survival.
- [X] I know that issues related to other plugins need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

**### An error occurred while loading**
`Error occurred while enabling RealisticSurvival v1.2.4-RELEASE (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.val_mobile.utils.TagList_v1_19_R1
	at me.val_mobile.utils.v1_19_R1.getTag(v1_19_R1.java:133) ~[?:?]
	at me.val_mobile.utils.Utils.getTag(Utils.java:637) ~[?:?]
	at me.val_mobile.utils.RSVRecipe.parseIng(RSVRecipe.java:98) ~[?:?]
	at me.val_mobile.utils.RSVRecipe.parseIngredient(RSVRecipe.java:139) ~[?:?]
	at me.val_mobile.utils.RSVShapedRecipe.getItems(RSVShapedRecipe.java:114) ~[?:?]
	at me.val_mobile.utils.RSVShapedRecipe.<init>(RSVShapedRecipe.java:49) ~[?:?]
	at me.val_mobile.data.RecipeManager.getRecipe(RecipeManager.java:85) ~[?:?]
	at me.val_mobile.data.RecipeManager.initialize(RecipeManager.java:61) ~[?:?]
	at me.val_mobile.data.RecipeManager.<init>(RecipeManager.java:43) ~[?:?]
	at me.val_mobile.data.ModuleRecipes.<init>(ModuleRecipes.java:24) ~[?:?]
	at me.val_mobile.spartanweaponry.SwModule.initialize(SwModule.java:48) ~[?:?]
	at me.val_mobile.realisticsurvival.RealisticSurvivalPlugin.onEnable(RealisticSurvivalPlugin.java:94) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:533) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:447) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:975) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3684-Spigot-41150f3-f770708]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: NON_FLAMMABLE_WOOD [in thread "Server thread"]
	at me.val_mobile.utils.TagList_v1_19_R1.<clinit>(TagList_v1_19_R1.java:132) ~[?:?]
	at me.val_mobile.utils.v1_19_R1.getTag(v1_19_R1.java:133) ~[?:?]
	at me.val_mobile.utils.Utils.getTag(Utils.java:637) ~[?:?]
	at me.val_mobile.utils.v1_17.getPickaxeMaterials(v1_17.java:13) ~[?:?]
	at me.val_mobile.utils.ToolUtils.<init>(ToolUtils.java:139) ~[?:?]
	at me.val_mobile.realisticsurvival.RealisticSurvivalPlugin.onEnable(RealisticSurvivalPlugin.java:82) ~[?:?]
	... 11 more`

### 📑 Reproduction Steps

1.using version 1.19.4
2.There are no other plugins

### 💡 Expected Behavior

I expect normal loading to happen
I think it's the right thing to do without an error

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Realistic Survival version

![image](https://github.com/ValMobile/RealisticSurvival/assets/123163148/2737ca2d-3322-41da-8304-7fa30b5aa0ed)

**Comment by ValMobile** [comment]
Issue should be solved as of 1.2.5 RELEASE
